"""A front page for a project directory.

Output is organised by the stage that produced it, which suits the pipeline
and not the person reading it: the pages someone opens are spread across
``report/``, ``demux_output/``, ``demux_output/streakout/``,
``demux_output/pileups/`` and ``pick/``, interleaved with reference indexes,
per-well FASTQs and logs.

This writes ``index.html`` at the top of the project, linking whatever exists
and saying what each thing is. It is regenerated by the commands that produce
those files, so it reflects the project as it stands rather than as it was
planned.
"""

from __future__ import annotations

import html as html_mod
from datetime import datetime
from pathlib import Path

from usortm.paths import integra_dir

INDEX_FILE = "index.html"


def _count(path: Path, pattern: str) -> int:
    return len(list(path.glob(pattern))) if path.is_dir() else 0


def _collect(project_dir: Path, round_num: int = 1) -> list:
    """Find what this project has produced.

    Returns:
        List of ``(section, title, href, note)``, only for things present.
    """
    demux = (project_dir / "rounds" / str(round_num) / "demux_output"
             if round_num > 1 else project_dir / "demux_output")
    report = (project_dir / "rounds" / str(round_num) / "report"
              if round_num > 1 else project_dir / "report")
    pick = project_dir / "pick"
    found = []

    live = demux / "live.html"
    if live.exists():
        age = datetime.now().timestamp() - live.stat().st_mtime
        note = ("updating now" if age < 120
                else f"last written {int(age // 60)} min ago")
        found.append(("While running", "Live dashboard", live, note))

    summary = report.parent / "summary.html"
    if summary.exists():
        found.append(("Results", "Summary report", summary,
                      "recovery, read depth, plate maps"))
    if (demux / "plate_map.html").exists():
        found.append(("Results", "Plate map", demux / "plate_map.html",
                      "wells by variant; click a well for its pileup"))

    for label, path, note in (
        ("All wells", demux / "pileups" / "index.html",
         "one pileup per well, grouped by plate"),
        ("Picked wells", pick / "pileup", "generated by usortm pick"),
        ("Streak-out candidates", demux / "streakout", "mixed-colony wells"),
        ("Mutated wells", demux / "mutation" / "pileup",
         "consensus differs from the library member"),
    ):
        if path.suffix == ".html":
            if path.exists():
                found.append(("Pileups", label, path, note))
        else:
            n = _count(path, "well_*.html")
            if n:
                found.append(("Pileups", label, path,
                              f"{n:,} wells — {note}"))

    for label, path, note in (
        ("Well assignments", demux / "well_assignments.csv",
         "one row per well: variant, depth, consensus"),
        ("Per-well summary", demux / "well_df.csv", "with reference lengths"),
        ("Per-read table", demux / "read_df.csv",
         "one row per read; no sequences"),
        ("Run summary", demux / "demux_summary.json", "aggregate counts"),
        ("Hit-picking list", integra_dir(pick),
         "Integra ASSIST transfer files"),
    ):
        if path.exists():
            found.append(("Data", label, path, note))

    return found


def write_index(project_dir, round_num: int = 1) -> Path:
    """Write ``index.html`` at the top of *project_dir* and return its path."""
    project_dir = Path(project_dir)
    items = _collect(project_dir, round_num)

    sections: dict = {}
    for section, title, path, note in items:
        try:
            href = path.relative_to(project_dir).as_posix()
        except ValueError:
            href = path.as_posix()
        if path.is_dir():
            href += "/"
        sections.setdefault(section, []).append((title, href, note))

    parts = [
        f"<title>{html_mod.escape(project_dir.name)}</title>",
        _STYLE,
        f"<main><h1>{html_mod.escape(project_dir.name)}</h1>",
        f'<p class="sub">uSort-M project'
        + (f" · round {round_num}" if round_num > 1 else "")
        + f' · index written {datetime.now():%d %b %H:%M}</p>',
    ]
    if not items:
        parts.append('<p class="empty">Nothing produced yet. Run '
                     "<code>usortm demux</code> to begin.</p>")
    for section in ("While running", "Results", "Pileups", "Data"):
        rows = sections.get(section)
        if not rows:
            continue
        parts.append(f"<h2>{section}</h2><ul>")
        for title, href, note in rows:
            parts.append(
                f'<li><a href="{html_mod.escape(href)}">'
                f"{html_mod.escape(title)}</a>"
                f'<span class="note">{html_mod.escape(note)}</span></li>'
            )
        parts.append("</ul>")
    parts.append("</main>")

    out = project_dir / INDEX_FILE
    out.write_text("\n".join(parts))
    return out


_STYLE = """<style>
  :root { color-scheme: light;
    --surface:#fcfcfb; --rule:#dedcd5; --text:#0b0b0b;
    --muted:#75736c; --link:#2a78d6; }
  @media (prefers-color-scheme: dark) {
    :root:where(:not([data-theme="light"])) {
      color-scheme: dark; --surface:#1a1a19; --rule:#3a3a37;
      --text:#fff; --muted:#96948a; --link:#7aa7ff; }
  }
  :root[data-theme="dark"] { color-scheme: dark;
    --surface:#1a1a19; --rule:#3a3a37; --text:#fff;
    --muted:#96948a; --link:#7aa7ff; }
  body { margin:0; background:var(--surface); color:var(--text);
         font:15px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif; }
  main { max-width:720px; margin:0 auto; padding:2.5rem 2rem; }
  h1 { font-size:1.3rem; margin:0 0 .2rem; }
  .sub { color:var(--muted); font-size:.87rem; margin:0 0 2rem; }
  h2 { font-size:.78rem; text-transform:uppercase; letter-spacing:.06em;
       color:var(--muted); margin:2rem 0 .5rem; font-weight:600; }
  ul { list-style:none; padding:0; margin:0; }
  li { padding:.55rem 0; border-bottom:1px solid var(--rule);
       display:flex; justify-content:space-between; gap:1.5rem;
       align-items:baseline; }
  a { color:var(--link); text-decoration:none; font-weight:500; }
  a:hover { text-decoration:underline; }
  .note { color:var(--muted); font-size:.83rem; text-align:right; }
  .empty { color:var(--muted); }
  code { background:var(--rule); padding:.1rem .35rem; border-radius:3px;
         font-size:.9em; }
</style>"""
