[meta]
name = "IDT gBlocks"
vendor = "IDT"
type = "arrayed"
date_collected = "2026-01-13"
notes = "Collected from IDT website"

[capabilities]
seq_length_min = 125
seq_length_max = 3000

[simulation]
error_rate = [1e-4, 3e-4]

[pricing]
model = "per_base"

[[pricing.rules]]
seq_length = [125, 3000]
per_base = 0.09

