[meta]
name = "IDT eBlocks"
vendor = "IDT"
type = "arrayed"
date_collected = "2026-03-06"
notes = ""

[capabilities]
seq_length_min = 300
seq_length_max = 1500

[simulation]
error_rate = [1e-4, 3e-4]

[pricing]
model = "per_base"

[[pricing.rules]]
seq_length = [300, 1500]
per_base = 0.07
