#!/usr/bin/env python3
"""Generate a barcoded plate of known constructs, with a known answer per well.

Useful for trying `usortm demux --expected` end to end.  One 96-well plate,
barcoded as quadrant TR of LevSeq plate 1 (RB02), holding single-codon
variants of one parent in a random backbone.  Most wells hold what the
expected CSV says; the rest are seeded with a swapped pair, a well holding
another well's construct, two wells carrying an extra mutation, two mixed
wells, three dropouts, a construct absent from the plate, and reads in two
wells expected empty.  truth.csv gives the verdict each well should get.

Usage:
    python scripts/make_plate_check_demo.py OUT_DIR [--seed N]

Then:
    usortm demux --expected OUT_DIR/expected.csv --fastq OUT_DIR/reads.fastq \\
        --vector OUT_DIR/parent_vector.fasta -o OUT_DIR/check
"""

import argparse
import csv
import sys
from pathlib import Path

import numpy as np

from usortm.demux.barcodes import LEVSEQ_FBC, LEVSEQ_RBC
from usortm.qc.synthetic import _apply_errors, _random_seq

OUTER_5P, OUTER_3P = "AATATAAATT", "ATAATTTATA"
_COMP = str.maketrans("ACGT", "TGCA")

README = """# Plate check example

A synthetic run for `usortm demux --expected`, generated by
`scripts/make_plate_check_demo.py` (seed {seed}).

## Inputs

| File | Contents |
|------|----------|
| `parent_vector.fasta` | The parent vector, {vector_len:,} bp, unmasked |
| `expected.csv` | What each well should hold: one 96-well plate barcoded as quadrant TR of LevSeq plate 1 (RB02) |
| `reads.fastq` | {n_reads:,} LevSeq reads at 2% substitution/indel error, in both orientations |
| `truth.csv` | The verdict each well should get, and what it really holds |

The plate holds {n_constructs} single-codon variants of one {insert_len} bp
parent, repeated across the plate. H10-H12 are expected empty.

## Seeded problems

| Wells | What was done | Expected verdict |
|-------|---------------|------------------|
| A1, A2 | Each holds the other's construct | wrong construct (swapped) |
| B5 | Holds the construct expected in C7 | wrong construct |
| C3, D8 | Carry one more codon change than expected | changed |
| E2, F9 | Two constructs, 50/50 and 60/40 | mixed |
| D1, E11, G6 | No reads | no reads |
| G12 | A construct that is nowhere on the plate | unrecognised |
| H10, H11 | Expected empty, but hold reads | unexpected reads |

## Run it

```bash
usortm demux --expected expected.csv --fastq reads.fastq \\
    --vector parent_vector.fasta -o check
```

`check/` holds the result of that command: open `check/plate_check.html` for
the plate map, and compare `check/verification.csv` with `truth.csv`.
"""


def _rc(s):
    return s.translate(_COMP)[::-1]


def make_demo(out: Path, seed: int = 7) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)
    up, down = _random_seq(rng, 1500), _random_seq(rng, 1500)
    p5, p3 = _random_seq(rng, 22), _random_seq(rng, 26)
    f5, f3 = _random_seq(rng, 150), _random_seq(rng, 200)
    parent = _random_seq(rng, 300)
    vector = up + p5 + f5 + parent + f3 + p3 + down
    (out / "parent_vector.fasta").write_text(f">parent_vector\n{vector}\n")

    def mutate(seq, pos):
        codon = seq[pos:pos + 3]
        while codon == seq[pos:pos + 3]:
            codon = _random_seq(rng, 3)
        return seq[:pos] + codon + seq[pos + 3:]

    constructs = {f"m{i:02d}": mutate(parent, 3 * (5 + 3 * i)) for i in range(24)}
    names = list(constructs)
    wells = [f"{r}{c}" for r in "ABCDEFGH" for c in range(1, 13)]
    expected = {w: names[i % 24] for i, w in enumerate(wells)}
    for w in ("H10", "H11", "H12"):
        expected[w] = None

    holds = {w: [(n, 1.0)] if n else [] for w, n in expected.items()}
    verdict = {w: "match" if n else "" for w, n in expected.items()}

    holds["A1"], holds["A2"] = [(expected["A2"], 1.0)], [(expected["A1"], 1.0)]
    holds["B5"] = [(expected["C7"], 1.0)]
    for w in ("A1", "A2", "B5"):
        verdict[w] = "wrong construct"
    extra = {}
    for w in ("C3", "D8"):
        extra[f"{w}_mut"] = mutate(constructs[expected[w]], 3 * 90)
        holds[w], verdict[w] = [(f"{w}_mut", 1.0)], "changed"
    holds["E2"] = [(expected["E2"], 0.5), (expected["E3"], 0.5)]
    holds["F9"] = [(expected["F9"], 0.6), (expected["G1"], 0.4)]
    verdict["E2"] = verdict["F9"] = "mixed"
    holds["H10"], holds["H11"] = [(names[3], 1.0)], [(names[9], 1.0)]
    verdict["H10"] = verdict["H11"] = "unexpected reads"
    for w in ("D1", "E11", "G6"):
        holds[w], verdict[w] = [], "no reads"
    extra["foreign"] = _random_seq(rng, 300)
    holds["G12"], verdict["G12"] = [("foreign", 1.0)], "unrecognised"
    seqs = {**constructs, **extra}

    with open(out / "expected.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["plate", "quadrant", "well", "name", "sequence"])
        for well in wells:
            n = expected[well]
            w.writerow([1, "TR", well, n or "", constructs[n] if n else ""])

    with open(out / "truth.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["well", "expected", "holds", "expected_verdict"])
        for well in wells:
            held = " + ".join(f"{n} ({p:.0%})" if p < 1 else n for n, p in holds[well])
            w.writerow([f"TR:{well}", expected[well] or "", held, verdict[well]])

    rbc = LEVSEQ_RBC[1]                        # RB02: plate 1, TR
    n_reads = 0
    with open(out / "reads.fastq", "w") as fh:
        for i, well in enumerate(wells):
            if not holds[well]:
                continue
            fbc = LEVSEQ_FBC[i]
            members, probs = zip(*holds[well])
            p = np.array(probs) / sum(probs)
            for k in range(int(rng.integers(30, 70))):
                n = members[int(rng.choice(len(members), p=p))]
                read = OUTER_5P + fbc + p5 + f5 + seqs[n] + f3 + p3 + _rc(rbc) + OUTER_3P
                if rng.random() < 0.5:
                    read = _rc(read)
                read = _apply_errors(rng, read, 0.02)
                fh.write(f"@{well}_{k}\n{read}\n+\n{'I' * len(read)}\n")
                n_reads += 1

    (out / "README.md").write_text(README.format(
        seed=seed, vector_len=len(vector), n_reads=n_reads,
        n_constructs=len(constructs), insert_len=len(parent)))
    return {"n_reads": n_reads, "wells": len(wells)}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[1],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("out_dir", type=Path, help="Directory to write into.")
    parser.add_argument("--seed", type=int, default=7, help="Random seed (default: 7).")
    args = parser.parse_args(argv)
    info = make_demo(args.out_dir, seed=args.seed)
    print(f"Wrote {info['wells']} wells, {info['n_reads']:,} reads to {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
